# Generated by Django 5.1.6 on 2025-05-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_manualattendancerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField(default='09:00')),
                ('shift_end', models.TimeField(default='17:00')),
                ('working_days', models.IntegerField(default=30)),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
    ]
