# Generated by Django 5.1.6 on 2025-05-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualattendancerequest',
            name='location_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
