[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[start]
cmd = "gunicorn AutomaticPayrollSystem.wsgi:application --bind 0.0.0.0:$PORT"
