# Generated by Django 5.1.6 on 2025-04-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_title_designation_name'),
        ('payroll', '0002_payroll_end_date_payroll_start_date_payroll_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='dailypayroll',
            unique_together={('employee', 'date')},
        ),
    ]
