# Generated by Django 5.1.6 on 2025-04-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_title_designation_name'),
        ('payroll', '0003_payroll_total_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField(default='09:00')),
                ('shift_end', models.TimeField(default='17:00')),
                ('working_days', models.IntegerField(default=30)),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'month')},
        ),
    ]
