# Generated by Django 5.1.6 on 2025-04-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollsettings_alter_payroll_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
