# Generated by Django 5.1.6 on 2025-04-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_payroll_total_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='total_salary',
            new_name='total_salary_genertaed',
        ),
    ]
