# Generated by Django 5.1.6 on 2025-04-07 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_remove_payroll_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
