# Generated by Django 5.1.6 on 2025-04-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_remove_payroll_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypayroll',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
