# Generated by Django 5.1.6 on 2025-04-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_dailypayroll_overtimepay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypayroll',
            name='daily_salary',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
