# Generated by Django 5.1.6 on 2025-05-26 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_payroll_performance_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollsettings',
            name='hours_per_day',
        ),
        migrations.RemoveField(
            model_name='payrollsettings',
            name='shift_end',
        ),
        migrations.RemoveField(
            model_name='payrollsettings',
            name='shift_start',
        ),
        migrations.RemoveField(
            model_name='payrollsettings',
            name='working_days',
        ),
    ]
