# Generated by Django 5.1.6 on 2025-03-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20250305_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='title',
            new_name='name',
        ),
    ]
