# Generated by Django 5.1.6 on 2025-05-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='remote_status',
            field=models.BooleanField(default=False),
        ),
    ]
