# Generated by Django 5.1.6 on 2025-06-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_data_remote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
    ]
