# Generated by Django 5.1.6 on 2025-04-30 23:30

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_title_designation_name'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='performancereview',
            old_name='reviewer_name',
            new_name='reviewed_by',
        ),
        migrations.RenameField(
            model_name='performancereview',
            old_name='comments',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='date',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='rating',
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='overall_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='period_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='period_start',
            field=models.DateField(default=datetime.datetime(2025, 4, 30, 23, 30, 52, 265311, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeperformance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='GoalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee_data')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateField(default=datetime.date.today)),
                ('reason', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee_data')),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.performancekpi')),
            ],
        ),
        migrations.AlterField(
            model_name='employeeperformance',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.performancekpi'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeperformance',
            unique_together={('employee', 'kpi', 'date')},
        ),
        migrations.DeleteModel(
            name='KPI',
        ),
    ]
