# Generated by Django 5.1.6 on 2025-05-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_title_designation_name'),
        ('leave_management', '0002_overtimeinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leaves', to='employees.employee_data'),
        ),
    ]
