# Generated by Django 5.1.6 on 2025-05-02 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_performancekpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
