# Generated by Django 5.1.6 on 2025-05-03 00:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_title_designation_name'),
        ('performance', '0003_performancereview_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('min_score', models.FloatField()),
                ('max_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('month', models.DateField(default=django.utils.timezone.now)),
                ('average_score', models.FloatField(default=0)),
                ('total_employees', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='performancealert',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='performancealert',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='employee',
        ),
        migrations.AlterUniqueTogether(
            name='employeeperformance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='performancekpi',
            name='description',
        ),
        migrations.RemoveField(
            model_name='performancekpi',
            name='name',
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='month',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancekpi',
            name='attendance_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='performancekpi',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee_data'),
        ),
        migrations.AddField(
            model_name='performancekpi',
            name='leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performancekpi',
            name='month',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='performancekpi',
            name='overtime_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='performancekpi',
            name='punctuality_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='performancekpi',
            name='task_completion_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeperformance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee_data'),
        ),
        migrations.AlterField(
            model_name='employeeperformance',
            name='kpi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='performance.performancekpi'),
        ),
        migrations.CreateModel(
            name='HRFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(default=3)),
                ('comments', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee_data')),
            ],
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='hr_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.hrfeedback'),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.performancegrade'),
        ),
        migrations.CreateModel(
            name='PerformanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateField(default=django.utils.timezone.now)),
                ('score', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee_data')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee_data')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.task')),
            ],
        ),
        migrations.DeleteModel(
            name='GoalSetting',
        ),
        migrations.DeleteModel(
            name='PerformanceAlert',
        ),
        migrations.DeleteModel(
            name='PerformanceReview',
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='score',
        ),
    ]
