# Generated by Django 5.1.6 on 2025-05-09 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_performancegrade_task_teamperformance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancekpi',
            name='overtime_hours',
        ),
    ]
