# Generated by Django 5.1.6 on 2025-05-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_remove_performancekpi_overtime_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceBonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score_threshold', models.DecimalField(decimal_places=2, default=90.0, max_digits=5)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
            ],
        ),
    ]
