# Generated by Django 5.1.6 on 2025-04-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_payroll_total_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
