# Generated by Django 5.1.6 on 2025-04-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_rename_total_salary_genertaed_payroll_total_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='start_date',
        ),
    ]
