# Generated by Django 5.1.6 on 2025-04-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_payroll_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='components',
        ),
        migrations.DeleteModel(
            name='PayrollComponent',
        ),
        migrations.DeleteModel(
            name='SalaryComponent',
        ),
    ]
