# Generated by Django 5.1.6 on 2025-04-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_payroll_bonus_payroll_overtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
