# Generated by Django 5.1.6 on 2025-04-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_dailypayroll_overtime_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailypayroll',
            name='overtime_pay',
        ),
        migrations.AlterField(
            model_name='dailypayroll',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='working_days',
            field=models.IntegerField(default=30),
        ),
    ]
