# Generated by Django 5.1.6 on 2025-04-08 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_remove_dailypayroll_overtime_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='overtime',
        ),
    ]
