# Generated by Django 5.1.6 on 2025-04-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_alter_dailypayroll_daily_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypayroll',
            name='daily_salary',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
