# Generated by Django 5.1.6 on 2025-05-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_alter_dailypayroll_daily_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='performance_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
