# Generated by Django 5.1.6 on 2025-06-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_rename_content_employeefeedback_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='is_resolved',
        ),
    ]
