# Generated by Django 5.1.6 on 2025-05-12 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_title_designation_name'),
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('responded_on', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee_data')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.leaverequest')),
            ],
        ),
    ]
