# Generated by Django 5.1.6 on 2025-05-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_leaverequest_assigned_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='emails_sent',
            field=models.BooleanField(default=False),
        ),
    ]
