# Generated by Django 5.1.6 on 2025-06-03 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_employee_data_remote_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('Harassment', 'Harassment'), ('Workload Issue', 'Workload Issue'), ('Salary Dispute', 'Salary Dispute'), ('Unfair Treatment', 'Unfair Treatment'), ('Workplace Safety', 'Workplace Safety'), ('Discrimination', 'Discrimination'), ('Other', 'Other')], max_length=50)),
                ('details', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee_data')),
            ],
        ),
    ]
