# Generated by Django 5.1.6 on 2025-06-03 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        ('employees', '0006_employee_data_remote_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bug Report', 'Bug Report'), ('Feature Request', 'Feature Request'), ('Usability Issue', 'Usability Issue'), ('Suggestion', 'Suggestion'), ('Other', 'Other')], max_length=50)),
                ('content', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee_data')),
            ],
        ),
    ]
