# Generated by Django 5.1.6 on 2025-06-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_employeefeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeefeedback',
            old_name='content',
            new_name='feedback',
        ),
        migrations.RemoveField(
            model_name='employeefeedback',
            name='category',
        ),
        migrations.AddField(
            model_name='employeefeedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeefeedback',
            name='suggestion',
            field=models.CharField(default='No feedback', max_length=255),
            preserve_default=False,
        ),
    ]
