# Generated by Django 5.1.6 on 2025-05-26 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_is_late'),
        ('employees', '0005_alter_employee_data_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manual_attendance_images/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee_data')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.location')),
            ],
        ),
    ]
